import express from "express";
import { createServer as createViteServer } from "vite";
import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '50mb' }));

  // API route for sending email
  app.post("/api/email-report", async (req, res) => {
    const { email, data, title } = req.body;

    if (!email || !data) {
      return res.status(400).json({ error: "Email and data are required" });
    }

    // Check for SMTP configuration
    const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM } = process.env;

    if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS) {
      console.error("SMTP configuration missing");
      return res.status(500).json({ 
        error: "Email service not configured. Please set SMTP environment variables." 
      });
    }

    try {
      const transporter = nodemailer.createTransport({
        host: SMTP_HOST,
        port: parseInt(SMTP_PORT || "587"),
        secure: SMTP_PORT === "465",
        auth: {
          user: SMTP_USER,
          pass: SMTP_PASS,
        },
      });

      const { title: reportTitle, analysis, notes } = data;
      const insights = analysis?.insights;
      const transcript = analysis?.transcript || [];
      
      // Create a readable HTML body
      const htmlBody = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #18181b;">
          <h1 style="font-size: 24px; font-weight: 800; margin-bottom: 8px;">Sales Call Analysis</h1>
          <p style="color: #71717a; margin-bottom: 24px;">Report for: <strong>${reportTitle || 'Untitled Call'}</strong></p>
          
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 700; border-bottom: 1px solid #e4e4e7; padding-bottom: 8px; margin-bottom: 16px;">Summary</h2>
            <p style="line-height: 1.6;">${insights?.summary || 'No summary available.'}</p>
          </div>

          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 700; border-bottom: 1px solid #e4e4e7; padding-bottom: 8px; margin-bottom: 16px;">Key Insights</h2>
            <div style="margin-bottom: 16px;">
              <h3 style="font-size: 14px; font-weight: 700; color: #059669; text-transform: uppercase;">Strengths</h3>
              <ul style="padding-left: 20px;">
                ${(insights?.strengths || []).map((s: string) => `<li style="margin-bottom: 4px;">${s}</li>`).join('') || '<li>None identified</li>'}
              </ul>
            </div>
            <div>
              <h3 style="font-size: 14px; font-weight: 700; color: #d97706; text-transform: uppercase;">Opportunities</h3>
              <ul style="padding-left: 20px;">
                ${(insights?.opportunities || []).map((o: string) => `<li style="margin-bottom: 4px;">${o}</li>`).join('') || '<li>None identified</li>'}
              </ul>
            </div>
          </div>

          ${notes ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 700; border-bottom: 1px solid #e4e4e7; padding-bottom: 8px; margin-bottom: 16px;">Notes</h2>
            <p style="white-space: pre-wrap; line-height: 1.6; background: #f4f4f5; padding: 16px; border-radius: 8px;">${notes}</p>
          </div>
          ` : ''}

          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 700; border-bottom: 1px solid #e4e4e7; padding-bottom: 8px; margin-bottom: 16px;">Transcript Highlights</h2>
            <div style="font-size: 14px;">
              ${transcript.slice(0, 10).map((s: any) => `
                <div style="margin-bottom: 12px;">
                  <span style="font-weight: 700; color: #4f46e5;">${s.speaker}:</span>
                  <p style="margin: 4px 0; color: #3f3f46;">${s.text}</p>
                </div>
              `).join('')}
              ${transcript.length > 10 ? '<p style="color: #71717a; font-style: italic;">... and more in the attached full report</p>' : ''}
            </div>
          </div>

          <p style="font-size: 12px; color: #a1a1aa; margin-top: 48px; border-top: 1px solid #e4e4e7; padding-top: 16px;">
            This report was generated by AI Sales Coach.
          </p>
        </div>
      `;

      const fileName = `${(title || 'call_analysis').replace(/\s+/g, '_')}.json`;

      await transporter.sendMail({
        from: SMTP_FROM || SMTP_USER,
        to: email,
        subject: `Sales Call Analysis: ${title || 'New Report'}`,
        html: htmlBody,
        attachments: [
          {
            filename: fileName,
            content: JSON.stringify(data, null, 2),
            contentType: 'application/json'
          }
        ]
      });

      res.json({ success: true });
    } catch (error: any) {
      console.error("Email sending error:", error);
      res.status(500).json({ error: "Failed to send email: " + error.message });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (req, res) => {
      res.sendFile("dist/index.html", { root: "." });
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
